name: jimamu
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^2.1.0
  path_provider: ^2.1.5
  get:
  get_storage:
  http:
  hive:
  hive_flutter:
  jwt_decoder:
  fluttertoast:
  flutter_screenutil:
  lottie:
  shimmer:
  firebase_core: ^3.13.0
  google_sign_in:
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  dio: ^5.8.0+1
  flutter_otp_text_field: ^1.5.1+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/auth/
    - assets/home/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
